### ISSUE TITLE
Support authenticating with AWS API via IAM instance roles

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-ec2-handler#4]
If the handler is running on an EC2 instance with IAM instance role associated, the IAM role should be used by default, making the aws key id and secret key optional.

**Comment by jgrasser** [comment]
I have opened a pull request against this issue. The code compiles on my laptop, but I am only a beginner golang dev so please let me know if there's something missing here. I also ran into some trouble testing this handler.

https://github.com/sensu/sensu-ec2-handler/pull/9
commit 6ea1a1ee46e4f947f44dad1859132331f9cadec4 (HEAD -> issue-4, origin/issue-4)
Author: Joseph Grasser <jgrasser@ifwe.co>
Date:   Sun 2020-03-22 14:34:46

    Use default credentials assigned to the host via instance-profile

    Modern security concerns eschew provisioning static credentials.
    I am not a golang developer; this is my first time working with
    the aws-go-sdk, so developer beware!
